### ISSUE TITLE
Compare selections

### ISSUE THREAD

**Issue by pwntester** [facelessuser/EasyDiff#15]
Would it be possible to compare two selections if two and only two selections are selected.

So if you use cmd to select two parts of the same view, can the menus show a new Compare selections options?

Thanks,
A

**Comment by facelessuser** [comment]
Menu portion is going to be handled in EasyDiff 2.0.0 via #21.  I plan on simplifying the menu system to eliminate the sub menus.  There will be a dedicated clipboard menu item in the future.  I will close this issue as tracking will be handled by #21.
