### ISSUE TITLE
Shortcuts for common tasks

### ISSUE THREAD

**Issue by lmartins** [facelessuser/EasyDiff#16]
Would it be possible to add shortcuts for common operations.
For example, Im using this mainly for comparing the current tab with the previously active, would be nice to have that accessible from a shortcut.

**Comment by facelessuser** [comment]
If you have the setting `quick_panel_commands` set to `True`, you can bind your desired action to a shortcut.  You want it to open in an external diff app, you must also have `show_external` enabled or `show_internal` for internal diffing.

### Current Tab/View Commands
Anyways, the command is pretty straight forward for comparing with the last active tab.  This command basically is applied to the current focused tab/view.  Methods are `view` to compare current tab with last active tab, `selection` to compare current selection with last active tab, `clipboard` to compare current tab with clipboard content, or `clipboard_selection` to compare current tab selection with clipboard content.

So below is the command where `method` is the desired method, and `external` is whether this is to be done internally in sublime, or sent to an external diff app.

```js
    {
        "command": "easy_diff_mru_panel_compare",
        "args": {"method": "view", "external": true}
    }
```

### Version Control
For version control diffs you would use either `easy_diff_<vc_system>` where `<vc_system>` is either `git`, `svn`, or `hg`. You this also has an `external` parameter and a `last` parameter.  When `last` is False it diffs current uncommitted changes.  When `last` is true, it should diff against previous revision. 

```js
    {
        "command": "easy_diff_<vc_system>",
        "args": {"external": true, "last": false}
    }
```

To revert a file, the command is called as a view command setting only `revert` to `true`:

```js
    {
        "command": "easy_diff_<vc_system>",
        "args": {"revert": true}
    }
```
