### ISSUE TITLE
Fails to detect file is part of HG repo

### ISSUE THREAD

**Issue by xenofanes9** [facelessuser/EasyDiff#17]
in hg.py, several calls to hgopen() are missing the second argument (dirname(target)), leading to EasyDiff reporting the file is not part of a repository because it uses the default CWD instead of the target directory.

**Comment by facelessuser** [comment]
Have you tried it with the second argument?  Are you sure that is the issue?  I haven't looked at this yet.

I think it is clear that I don't actually use mercurial much, so if you know what the problem is and can verify that it fixes the issue, a pull request would be appreciated.

**Comment by xenofanes9** [comment]
Yes, I modified my local copy and it works great.  I'm new to the git flow, but expect a pull request shortly...

**Comment by facelessuser** [comment]
HG fixed was merged.
