### ISSUE TITLE
Windows, delay on right click menu for file on remote network

### ISSUE THREAD

**Issue by johndrummond** [facelessuser/EasyDiff#28]
I installed EasyDiff,  - using windows, and noticed that for a file on a remote network directory, the right click menu would only come up after several seconds.
The same file locally would give no problem.
I disabled EasyDiff and the the right click menu on the remote file worked again.
The remote network isn't fast and may have peculiar permissions, but the effect was there with the plugin enabled and not with the plugin disable.
Kind Regards, John.

**Comment by facelessuser** [comment]
When the menu is first accessed, EasyDiff will have a delay as it will assess which of the enabled VC implementations it can use.  After the first time, this should be quicker.

In regards to network files, yes, this can potentially take a bit for it to discover if the file is version controlled. You can disable this autocheck:

```js
    // Do not perform a version check on files
    // when evaluating whether version control
    // commands are enabled.  May avoid slowing
    // down context menu draw in large version
    // controlled projects.
    "skip_version_check_on_is_enabled": true,
```

**Comment by facelessuser** [comment]
I assume this question has been answered, so I am closing this issue.  If you feel the question wasn't answered, feel free to elaborate and reopen.
