### ISSUE TITLE
EasyDiff slows down context menu due to many git, svn and hg process spawns in sequence on Windows

### ISSUE THREAD

**Issue by alshain** [facelessuser/EasyDiff#30]
The right click menu in my one Git project takes about ~5 to 15 seconds to open.

I have noticed that this delay disappears entirely when I disable EasyDiff, enabling it brings the phenomenon back.

Procmon shows that plugin_host.exe spawns many git processes in sequence, also some svn and some hg processes.

The timestamps on these processes correspond exactly with when I press rightclick and when the context menu eventually appears. The two time stamps are start and end time of the process, respectively.

In this image (EasyDiff enabled) you that VCS related processes started for about 12 seconds for the context menu, that's with EasyDiff enabled:
![image](https://user-images.githubusercontent.com/349397/49281164-25b4ba00-f48c-11e8-8bc9-909a94acc746.png)
This is a project with thousands of small files, most of which are ignored through .gitignore

Without EasyDiff, there are no git invocations that coincide with the opening of the context menu:
![image](https://user-images.githubusercontent.com/349397/49281549-2437c180-f48d-11e8-9ecc-443e28492ab0.png)
I opened the context menu at 10:44:25 and again at 10:44:30 and stopped recording at 10:44:36. As you cans see, zero processes started during that time by plugin_host.exe

I have also closed sublime and reopened it in an completely new folder and put an empty txt file in it. The folder is near the root of the drive such that no program needs to traverse many parents to look for a VCS root.
This is the result when I right-click within that file
![image](https://user-images.githubusercontent.com/349397/49282163-c2785700-f48e-11e8-9289-25c9b262130e.png)

The right click menu took several seconds to open. Again, the phenomenon goes away completely when I disable EasyDiff.

Related: #10 

Any thoughts on this issue?

Running Windows 10, latest updates, x64

**Comment by alshain** [comment]
I've had this plugin installed for a long time now. Unfortunately I can't recall when it started. I just took the time today to figure out what was causing the delay in the right click menu.

**Comment by facelessuser** [comment]
As mentioned `skip_version_check_on_is_enabled` should stop EasyDiff from checking if the targeted file is version controlled to reduce lag, the first time the context menu is shown, EasyDiff will still have some lag when it checks if the version control executables are present and functioning.

I've went ahead and implemented instead a check that only checks that the binaries are present.  This will do so with out calls to the libraries and thereby eliminate the overhead of such calls.  See #31 for more info.

**Comment by facelessuser** [comment]
Change has been released.
