### ISSUE TITLE
Latency when right clicking

### ISSUE THREAD

**Issue by Vzor-** [facelessuser/EasyDiff#33]
This adds a noticeable latency to right clicks in Sublime Text 3 on Windows.

**Comment by facelessuser** [comment]
You may be looking for this:

```js
    // Do not perform a version check on files
    // when evaluating whether version control
    // commands are enabled.  May avoid slowing
    // down context menu draw in large version
    // controlled projects.
    "skip_version_check_on_is_enabled": false,
```

**Comment by facelessuser** [comment]
I want to say that the first time you open the menu it may also be slow as I think I delay the check of seeing which version control systems are available until the first time you open the menu. After the initial menu, that check is no longer performed.

**Comment by Vzor-** [comment]
> 
> 
> You may be looking for this:
> 
> ```js
>     // Do not perform a version check on files
>     // when evaluating whether version control
>     // commands are enabled.  May avoid slowing
>     // down context menu draw in large version
>     // controlled projects.
>     "skip_version_check_on_is_enabled": false,
> ```

That did it, thanks. It was in a project with an extensive commit history.

**Comment by facelessuser** [comment]
Yup. Figured that was it.
