### ISSUE TITLE
Reduce dependencies

### ISSUE THREAD

**Issue by deathaxe** [facelessuser/EasyDiff#34]
Does it make sense to reduce dependencies to only `mdpopups`?

```
{
    "*": {
        ">=3124": [
            "mdpopups"
        ]
    }
}
```

It appears to come along with everything needed and is itself only needed for `support.py`.

**Comment by facelessuser** [comment]
I'll be a bit more direct, is there a specific reason you desire it to not include this? If you rely on certain packages I maintain, it is going to be included anyway. If you use LSP, it is going to be included anyway, so I'm curious if there is something else driving this.

**Comment by facelessuser** [comment]
Oh, I get it now. Yes, moving forward, I just include `mdpopups`. I haven't explicitly updated this package in a while as it is, for the most part, a complete package. For that reason, I just hadn't updated the dependencies. In that case, yes, I can reduce the dependencies.

**Comment by facelessuser** [comment]
I merged your PR.
