### ISSUE TITLE
Sublime Text 4 Support

### ISSUE THREAD

**Issue by pa-0** [facelessuser/EasyDiff#36]
Hello, I notice that EasyDiff's support documentation identifies ST3 exclusively with respect to fully supported and maintained versions of Sublime Text.  Are there any plans to support ST4 as well (beyond welcoming PRs from community contributors)?

At any rate, thanks for sharing this nifty extension! 😁

**Comment by facelessuser** [comment]
It supports the latest. I still use this plugin, so as long as I do, I still support it.

**Comment by pa-0** [comment]
Good to hear! Thanks for getting back to me so quickly.
