### ISSUE TITLE
External tool doesn't show up in the menus

### ISSUE THREAD

**Issue by ChristinWhite** [facelessuser/EasyDiff#8]
Hey there,

Thanks for creating such an excellent package, it's far easier to use and configure than some of the other options!

I am, however, having a  little trouble getting the external tool option to work. I'd like to setup EasyDiff to let me use [Kaleidoscope](http://www.kaleidoscopeapp.com), I've installed the [Command-Line Tool](http://www.kaleidoscopeapp.com/ksdiff2?v=116.01) and using the following syntax in the Terminal works fine:

![kaleidoscope_command-line_tool-2](https://f.cloud.github.com/assets/1746405/1761463/64021348-66cf-11e3-81af-fa8ad47a8bc8.png)

I think I have things setup correctly in the preferences (/Users/cwhite/Library/Application Support/Sublime Text 3/Packages/User/easy_diff.sublime-settings).

``` json
{
    // Show internal diff options (Easy Diff in a view or buffer)
    "show_internal": true,

    // Show external options (options to send files to external diff tool)
    "show_external": true,

    // External diff tool path (absolute)
    "external_diff": "ksdiff",

    // Turn off svn completely
    "svn_disabled": true,

    // Turn off git completely
    "git_disabled": false,

    // Turn off (Mercurial) hg completely
    "hg_disabled": true,
}
```

But I don't see any option to open the file in an external diff tool anywhere in the context menu. 

**I've tried...**
1. Setting `show_internal` to `false` to make sure they weren't overwriting each other.
2. Specifying the full path to ksdiff as `/usr/bin/ksdiff` (the symlink) and `/Applications/Kaleidoscope.app/Contents/MacOS/ksdiff` (the actual file).

I know the settings file is working correctly because disabling internal or any of the source control options works fine.

**System**
- OS X 10.9
- Sublime Text Stable Channel, Build 3047
- EasyDiff 2013.11.27.02.56.58

Any ideas?

Thanks!

**Comment by lmartins** [comment]
Brilliant, was looking for setting up Kaleidoscope with EasyDiff and this helped me a lot. Thank you both!

**Comment by iyee** [comment]
@facelessuser I met the same problem when configuring with Beyond Compare, my settings:
```
{
    // Show internal diff options (Easy Diff in a view or buffer)
    "show_internal": true,

    // Show external options (options to send files to external diff tool)
    "show_external": true,

    // External diff tool path (absolute)
    "external_diff": "/usr/local/bin/bcomp",

    // Turn off svn completely
    "svn_disabled": true,

    // Turn off git completely
    "git_disabled": false,

    // Turn off (Mercurial) hg completely
    "hg_disabled": true,

    // Turn off svn menu access
    "svn_hide_menu": true,

    // Turn off git menu access
    "git_hide_menu": false,

    // Turn off (Mercurial) hg menu access
    "hg_hide_menu": true
}
```

console log:
```
EasyDiff: svn 1.7.22
EasyDiff: git 2.8.0
EasyDiff: hg not found or is not working!
```

there's no external tool context menu.
<img width="392" alt="screen shot 2016-06-01 at 18 37 28" src="https://cloud.githubusercontent.com/assets/88564/15706796/f0f92d56-2827-11e6-86c9-c2e6411ec059.png">

**Comment by facelessuser** [comment]
Since I use Beyond Compare on all my machines and OSs, I know this works for me on OSX.  I'm not sure which Beyond Compare you are using, but I am using the latest.  External commands will be found under `Diff` not `EasyDiff`.  I use the `EasyDiff` for diff commands done inside Sublime.  Commands that call outside to external diff binaries are found under `Diff` entries.

```js
    "show_external": true,
    "external_diff": "/usr/local/bin/bcomp",
```
